elasticsearch:
  image: elasticsearch:5
  ports:
    - 9200:9200
    - 9300:9300
  volumes:
    - ./elasticsearch/data/:/usr/share/elasticsearch/data/
kibana:
  image: kibana:5
  ports:
    - 5601:5601
  links:
    - elasticsearch
  environment:
    - ELASTICSEARCH_URL=http://192.168.33.10:9200
